package jcc1;

public class Adder {

    public int sum(int[] a) {
        int sum = 0;
        for (int i : a) sum += i;
        return sum;
    }

    public void addConst(int c, int[] a) {
        for (int i = 0; i < a.length; i++) {
            a[i] += c;
        }
    }

    public void didYouCoverMe(boolean b) {
        if (b) {
            System.out.println("Hello, test generated by Kex, did you cover me?");
        } else {
            System.out.println("You did, right?");
        }
    }

    public void introduce() {
        System.out.printf("Hello, I am %s.%n", getClass());
    }
}
